---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  TZ: "America/Denver"
  DNS1: "1.1.1.1"
  DNS2: "1.0.0.1"
  DNSMASQ_LISTENING: "all"
  VIRTUAL_HOST: "pihole.local"
