---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 67
              name: dhcp
              protocol: UDP
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: TZ
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: WEBPASSWORD
            - name: DNS1
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: DNS1
            - name: DNS2
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: DNS2
            - name: DNSMASQ_LISTENING
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: DNSMASQ_LISTENING
            - name: VIRTUAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: VIRTUAL_HOST
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /admin
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /admin
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
      securityContext:
        fsGroup: 999
